"""
Step 4 — Update configuration for enterprise profile.

Generates a new ``.env`` file with enterprise settings and updates
Docker Compose configuration:

1. Read current ``.env`` values
2. Generate enterprise ``.env`` with profile=full
3. Backup current ``.env``
4. Configure enterprise services (PostgreSQL, Qdrant, Redis)
5. Validate the new configuration

Usage::

    python scripts/migrate_enterprise/04_update_config.py
    python scripts/migrate_enterprise/04_update_config.py --dry-run
"""

from __future__ import annotations

import logging
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("migrate.config")


# ---------------------------------------------------------------------------
# .env template for enterprise
# ---------------------------------------------------------------------------

ENTERPRISE_ENV_TEMPLATE = """\
# ===========================================================================
# KnowledgeHub — Enterprise Configuration
# Generated by migration script on {timestamp}
# ===========================================================================

# ── Profile ────────────────────────────────────────────────────────────────
KNOWLEDGEHUB_PROFILE=full

# ── Database (PostgreSQL) ──────────────────────────────────────────────────
KNOWLEDGEHUB_DATABASE_URL={database_url}
KNOWLEDGEHUB_DB_POOL_SIZE={db_pool_size}
KNOWLEDGEHUB_DB_MAX_OVERFLOW={db_max_overflow}

# ── Vector Store (Qdrant) ─────────────────────────────────────────────────
KNOWLEDGEHUB_VECTORSTORE_BACKEND=qdrant
KNOWLEDGEHUB_QDRANT_HOST={qdrant_host}
KNOWLEDGEHUB_QDRANT_PORT={qdrant_port}
KNOWLEDGEHUB_QDRANT_COLLECTION={qdrant_collection}

# ── LLM Backend (vLLM) ────────────────────────────────────────────────────
KNOWLEDGEHUB_LLM_BACKEND=vllm
KNOWLEDGEHUB_VLLM_BASE_URL={vllm_base_url}
KNOWLEDGEHUB_VLLM_MODEL={vllm_model}
KNOWLEDGEHUB_VLLM_MAX_TOKENS={vllm_max_tokens}

# ── Embeddings ─────────────────────────────────────────────────────────────
KNOWLEDGEHUB_EMBEDDING_BACKEND={embedding_backend}
KNOWLEDGEHUB_EMBEDDING_MODEL={embedding_model}
KNOWLEDGEHUB_EMBEDDING_DIMENSION={embedding_dimension}
KNOWLEDGEHUB_EMBEDDING_BATCH_SIZE={embedding_batch_size}
KNOWLEDGEHUB_OLLAMA_EMBEDDING_MODEL={ollama_embedding_model}

# ── Ollama (kept for embeddings if needed) ─────────────────────────────────
KNOWLEDGEHUB_OLLAMA_BASE_URL={ollama_base_url}

# ── Service Ports ──────────────────────────────────────────────────────────
KNOWLEDGEHUB_GATEWAY_PORT={gateway_port}
KNOWLEDGEHUB_ADMIN_PORT={admin_port}

# ── Security ───────────────────────────────────────────────────────────────
KNOWLEDGEHUB_SECRET_KEY={secret_key}
KNOWLEDGEHUB_API_KEYS={api_keys}

# ── Logging ────────────────────────────────────────────────────────────────
KNOWLEDGEHUB_LOG_LEVEL={log_level}
KNOWLEDGEHUB_LOG_FORMAT=json

# ── Knowledge Processing ──────────────────────────────────────────────────
KNOWLEDGEHUB_CHUNK_SIZE={chunk_size}
KNOWLEDGEHUB_CHUNK_OVERLAP={chunk_overlap}

# ── Open WebUI ─────────────────────────────────────────────────────────────
KNOWLEDGEHUB_OPENWEBUI_URL={openwebui_url}

# ===========================================================================
# Enterprise Features
# ===========================================================================

# ── Authentication ─────────────────────────────────────────────────────────
# Options: none, oidc, ldap
KNOWLEDGEHUB_ENTERPRISE_AUTH_PROVIDER={auth_provider}
# KNOWLEDGEHUB_ENTERPRISE_OIDC_ISSUER=https://your-idp.example.com
# KNOWLEDGEHUB_ENTERPRISE_OIDC_CLIENT_ID=knowledgehub
# KNOWLEDGEHUB_ENTERPRISE_LDAP_SERVER_URL=ldap://ldap.example.com:389
# KNOWLEDGEHUB_ENTERPRISE_LDAP_BASE_DN=dc=example,dc=com

# ── Audit Trail ────────────────────────────────────────────────────────────
KNOWLEDGEHUB_ENTERPRISE_AUDIT_ENABLED={audit_enabled}
KNOWLEDGEHUB_ENTERPRISE_AUDIT_RETENTION_DAYS={audit_retention_days}

# ── Multi-tenancy ─────────────────────────────────────────────────────────
KNOWLEDGEHUB_ENTERPRISE_MULTITENANCY_ENABLED={multitenancy_enabled}
KNOWLEDGEHUB_ENTERPRISE_DEFAULT_TENANT={default_tenant}

# ── Clustering / High Availability ────────────────────────────────────────
KNOWLEDGEHUB_ENTERPRISE_CLUSTER_ENABLED={cluster_enabled}
KNOWLEDGEHUB_ENTERPRISE_REDIS_URL={redis_url}

# ── Monitoring ─────────────────────────────────────────────────────────────
KNOWLEDGEHUB_ENTERPRISE_METRICS_ENABLED={metrics_enabled}
KNOWLEDGEHUB_ENTERPRISE_TRACING_ENABLED={tracing_enabled}
# KNOWLEDGEHUB_ENTERPRISE_OTLP_ENDPOINT=http://otel-collector:4317

# ── Enterprise Backup ─────────────────────────────────────────────────────
KNOWLEDGEHUB_ENTERPRISE_BACKUP_ENABLED={backup_enabled}
KNOWLEDGEHUB_ENTERPRISE_BACKUP_INTERVAL_HOURS={backup_interval_hours}
# KNOWLEDGEHUB_ENTERPRISE_BACKUP_ENCRYPTION_KEY=your-encryption-key
# KNOWLEDGEHUB_ENTERPRISE_BACKUP_S3_ENDPOINT=https://s3.amazonaws.com
# KNOWLEDGEHUB_ENTERPRISE_BACKUP_S3_BUCKET=knowledgehub-backups
"""


def _read_current_env(env_path: str = ".env") -> dict[str, str]:
    """Parse the current .env file into a dict."""
    values: dict[str, str] = {}
    p = Path(env_path)
    if not p.exists():
        return values

    for line in p.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()

    return values


def _get_value(
    current: dict[str, str], key: str, default: str,
) -> str:
    """Get a value from current env or environment, with fallback."""
    env_val = os.environ.get(key, "")
    cur_val = current.get(key, "")
    return env_val or cur_val or default


def generate_enterprise_env(
    current_env: dict[str, str] | None = None,
) -> str:
    """Generate the enterprise .env file content."""
    current = current_env or _read_current_env()
    now = datetime.now(timezone.utc).isoformat()

    values: dict[str, Any] = {
        "timestamp": now,
        # Database
        "database_url": _get_value(
            current, "KNOWLEDGEHUB_DATABASE_URL",
            "postgresql+asyncpg://knowledgehub:changeme@postgres:5432/knowledgehub",
        ),
        "db_pool_size": _get_value(current, "KNOWLEDGEHUB_DB_POOL_SIZE", "10"),
        "db_max_overflow": _get_value(current, "KNOWLEDGEHUB_DB_MAX_OVERFLOW", "20"),
        # Qdrant
        "qdrant_host": _get_value(current, "KNOWLEDGEHUB_QDRANT_HOST", "qdrant"),
        "qdrant_port": _get_value(current, "KNOWLEDGEHUB_QDRANT_PORT", "6333"),
        "qdrant_collection": _get_value(current, "KNOWLEDGEHUB_QDRANT_COLLECTION", "knowledgehub"),
        # LLM
        "vllm_base_url": _get_value(current, "KNOWLEDGEHUB_VLLM_BASE_URL", "http://vllm:8000"),
        "vllm_model": _get_value(
            current, "KNOWLEDGEHUB_VLLM_MODEL", "meta-llama/Llama-3.1-8B-Instruct",
        ),
        "vllm_max_tokens": _get_value(current, "KNOWLEDGEHUB_VLLM_MAX_TOKENS", "2048"),
        # Embeddings
        "embedding_backend": _get_value(current, "KNOWLEDGEHUB_EMBEDDING_BACKEND", "ollama"),
        "embedding_model": _get_value(current, "KNOWLEDGEHUB_EMBEDDING_MODEL", "all-MiniLM-L6-v2"),
        "embedding_dimension": _get_value(current, "KNOWLEDGEHUB_EMBEDDING_DIMENSION", "768"),
        "embedding_batch_size": _get_value(current, "KNOWLEDGEHUB_EMBEDDING_BATCH_SIZE", "128"),
        "ollama_embedding_model": _get_value(
            current, "KNOWLEDGEHUB_OLLAMA_EMBEDDING_MODEL", "nomic-embed-text",
        ),
        # Ollama
        "ollama_base_url": _get_value(current, "KNOWLEDGEHUB_OLLAMA_BASE_URL", "http://ollama:11434"),
        # Ports (preserve current)
        "gateway_port": _get_value(current, "KNOWLEDGEHUB_GATEWAY_PORT", "8000"),
        "admin_port": _get_value(current, "KNOWLEDGEHUB_ADMIN_PORT", "8001"),
        # Security (preserve current)
        "secret_key": _get_value(current, "KNOWLEDGEHUB_SECRET_KEY", "change-this-to-a-random-secret-key"),
        "api_keys": _get_value(current, "KNOWLEDGEHUB_API_KEYS", ""),
        # Logging
        "log_level": _get_value(current, "KNOWLEDGEHUB_LOG_LEVEL", "info"),
        # Knowledge
        "chunk_size": _get_value(current, "KNOWLEDGEHUB_CHUNK_SIZE", "1024"),
        "chunk_overlap": _get_value(current, "KNOWLEDGEHUB_CHUNK_OVERLAP", "100"),
        # Open WebUI
        "openwebui_url": _get_value(current, "KNOWLEDGEHUB_OPENWEBUI_URL", "http://localhost:3000"),
        # Enterprise defaults
        "auth_provider": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_AUTH_PROVIDER", "none"),
        "audit_enabled": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_AUDIT_ENABLED", "false"),
        "audit_retention_days": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_AUDIT_RETENTION_DAYS", "90"),
        "multitenancy_enabled": _get_value(
            current, "KNOWLEDGEHUB_ENTERPRISE_MULTITENANCY_ENABLED", "false",
        ),
        "default_tenant": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_DEFAULT_TENANT", "default"),
        "cluster_enabled": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_CLUSTER_ENABLED", "false"),
        "redis_url": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_REDIS_URL", ""),
        "metrics_enabled": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_METRICS_ENABLED", "true"),
        "tracing_enabled": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_TRACING_ENABLED", "false"),
        "backup_enabled": _get_value(current, "KNOWLEDGEHUB_ENTERPRISE_BACKUP_ENABLED", "false"),
        "backup_interval_hours": _get_value(
            current, "KNOWLEDGEHUB_ENTERPRISE_BACKUP_INTERVAL_HOURS", "24",
        ),
    }

    # Force PostgreSQL URL
    if "sqlite" in values["database_url"]:
        values["database_url"] = (
            "postgresql+asyncpg://knowledgehub:changeme@postgres:5432/knowledgehub"
        )

    return ENTERPRISE_ENV_TEMPLATE.format(**values)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def update_config(dry_run: bool = False) -> dict[str, Any]:
    """Generate and write the enterprise configuration.

    Returns a summary dict with paths and changes made.
    """
    logger.info("=" * 60)
    logger.info("KnowledgeHub — Configuration Update (mini → enterprise)")
    if dry_run:
        logger.info("MODE: DRY RUN")
    logger.info("=" * 60)

    env_path = Path(".env")
    result: dict[str, Any] = {"changes": []}

    # Read current
    current = _read_current_env(str(env_path))
    logger.info("Current profile: %s", current.get("KNOWLEDGEHUB_PROFILE", "mini"))

    # Generate new .env
    new_env_content = generate_enterprise_env(current)

    if dry_run:
        logger.info("Generated .env preview (first 40 lines):")
        for line in new_env_content.splitlines()[:40]:
            logger.info("  %s", line)
        result["dry_run"] = True
        return result

    # Backup current .env
    if env_path.exists():
        backup_name = f".env.backup.{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
        shutil.copy2(env_path, backup_name)
        logger.info("Backed up current .env → %s", backup_name)
        result["changes"].append(f"Backed up .env to {backup_name}")

    # Write new .env
    env_path.write_text(new_env_content)
    logger.info("Written new enterprise .env")
    result["changes"].append("Written new .env with profile=full")

    # Create docker-compose.override.yml to use enterprise compose
    override_path = Path("docker-compose.override.yml")
    if not override_path.exists():
        override_content = (
            "# Auto-generated by migration script\n"
            "# This file extends docker-compose.yml with enterprise services.\n"
            "# To use: docker compose -f docker-compose.yml "
            "-f docker-compose.enterprise.yml up -d\n"
        )
        override_path.write_text(override_content)
        logger.info("Created docker-compose.override.yml")
        result["changes"].append("Created docker-compose.override.yml")

    logger.info("-" * 60)
    logger.info("Configuration update COMPLETE")
    logger.info("Next: start enterprise services with:")
    logger.info("  docker compose -f docker-compose.yml -f docker-compose.enterprise.yml up -d")

    result["env_path"] = str(env_path)
    return result


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    update_config(dry_run=dry_run)


if __name__ == "__main__":
    main()
