#!/usr/bin/env bash
# =============================================================================
# KnowledgeHub + Open WebUI Setup Script
#
# Automates the deployment of Open WebUI integrated with KnowledgeHub.
# Supports both Pipeline mode and Proxy mode.
#
# Usage:
#   bash scripts/setup_openwebui.sh [--proxy-only] [--no-start]
#
# Options:
#   --proxy-only   Skip pipeline installation, use proxy mode only
#   --no-start     Generate configs but don't start containers
# =============================================================================

set -euo pipefail

# ── Colors ─────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Defaults ───────────────────────────────────────────────────────────────
PROXY_ONLY=false
NO_START=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

OPEN_WEBUI_PORT="${OPEN_WEBUI_PORT:-3000}"
GATEWAY_URL="${KNOWLEDGEHUB_GATEWAY_URL:-http://gateway:8000}"
OLLAMA_URL="${OLLAMA_BASE_URL:-http://ollama:11434}"

# ── Parse args ─────────────────────────────────────────────────────────────
for arg in "$@"; do
    case "$arg" in
        --proxy-only) PROXY_ONLY=true ;;
        --no-start)   NO_START=true ;;
        -h|--help)
            echo "Usage: $0 [--proxy-only] [--no-start]"
            echo ""
            echo "Options:"
            echo "  --proxy-only   Use proxy mode only (no pipeline)"
            echo "  --no-start     Generate config files without starting containers"
            exit 0
            ;;
        *)
            error "Unknown option: $arg"
            exit 1
            ;;
    esac
done

# ── Pre-flight checks ─────────────────────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    error "Docker is not installed. Please install Docker first."
    exit 1
fi
success "Docker found"

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
    error "Docker Compose is not installed."
    exit 1
fi
success "Docker Compose found"

# Determine docker compose command
if docker compose version &>/dev/null; then
    DC="docker compose"
else
    DC="docker-compose"
fi

cd "$PROJECT_DIR"
info "Working directory: $PROJECT_DIR"

# ── Check KnowledgeHub is running ─────────────────────────────────────────
info "Checking if KnowledgeHub gateway is running..."

GATEWAY_LOCAL_URL="${KNOWLEDGEHUB_GATEWAY_URL:-http://localhost:8000}"
if curl -sf "${GATEWAY_LOCAL_URL}/health" >/dev/null 2>&1; then
    success "KnowledgeHub gateway is healthy"
else
    warn "KnowledgeHub gateway is not reachable at ${GATEWAY_LOCAL_URL}"
    warn "Make sure to start it before using Open WebUI:"
    warn "  $DC up -d"
fi

# ── Generate docker-compose.openwebui.yml ─────────────────────────────────
info "Generating docker-compose.openwebui.yml..."

PIPELINE_VOLUMES=""
PIPELINE_ENV=""

if [ "$PROXY_ONLY" = false ]; then
    PIPELINE_VOLUMES="      - ./pipelines:/app/backend/pipelines"
    PIPELINE_ENV="      - KNOWLEDGEHUB_GATEWAY_URL=${GATEWAY_URL}"
    info "Mode: Pipeline + Proxy (full integration)"
else
    info "Mode: Proxy only (no pipeline)"
fi

cat > docker-compose.openwebui.yml <<YAML
# =============================================================================
# Open WebUI integration with KnowledgeHub
# Generated by scripts/setup_openwebui.sh
#
# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.openwebui.yml up -d
# =============================================================================

version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: knowledgehub-open-webui
    ports:
      - "${OPEN_WEBUI_PORT}:8080"
    environment:
      - WEBUI_AUTH=false
      - OLLAMA_BASE_URL=${OLLAMA_URL}
      - ENABLE_OPENAI_API=true
      - OPENAI_API_BASE_URL=${GATEWAY_URL}/v1
      - OPENAI_API_KEY=knowledgehub
${PIPELINE_ENV}
    volumes:
      - open-webui-data:/app/backend/data
${PIPELINE_VOLUMES}
    depends_on:
      - gateway
      - ollama
    restart: unless-stopped
    networks:
      - knowledgehub

volumes:
  open-webui-data:

networks:
  knowledgehub:
    external: true
YAML

success "Created docker-compose.openwebui.yml"

# ── Verify pipeline file exists ───────────────────────────────────────────
if [ "$PROXY_ONLY" = false ]; then
    if [ -f "pipelines/knowledgehub_pipeline.py" ]; then
        success "Pipeline file found: pipelines/knowledgehub_pipeline.py"
    else
        error "Pipeline file not found: pipelines/knowledgehub_pipeline.py"
        error "Please ensure the pipeline file exists before starting."
        exit 1
    fi
fi

# ── Start services ─────────────────────────────────────────────────────────
if [ "$NO_START" = true ]; then
    info "Skipping container start (--no-start flag)"
    echo ""
    info "To start everything manually:"
    echo "  $DC -f docker-compose.yml -f docker-compose.openwebui.yml up -d"
    exit 0
fi

# Ensure the KnowledgeHub network exists
info "Ensuring Docker network exists..."
if ! docker network inspect knowledgehub_knowledgehub &>/dev/null 2>&1; then
    info "Starting KnowledgeHub stack first to create the network..."
    $DC up -d
    success "KnowledgeHub stack started"
else
    success "Docker network knowledgehub_knowledgehub exists"
fi

info "Starting Open WebUI..."
$DC -f docker-compose.yml -f docker-compose.openwebui.yml up -d open-webui

# ── Wait for Open WebUI to be ready ───────────────────────────────────────
info "Waiting for Open WebUI to start..."
MAX_WAIT=60
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    if curl -sf "http://localhost:${OPEN_WEBUI_PORT}" >/dev/null 2>&1; then
        break
    fi
    sleep 2
    WAITED=$((WAITED + 2))
    printf "."
done
echo ""

if [ $WAITED -ge $MAX_WAIT ]; then
    warn "Open WebUI did not respond within ${MAX_WAIT}s"
    warn "Check logs: docker logs knowledgehub-open-webui"
else
    success "Open WebUI is ready!"
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
info "Setup complete!"
echo ""
echo "  Open WebUI:          http://localhost:${OPEN_WEBUI_PORT}"
echo "  KnowledgeHub Gateway: ${GATEWAY_LOCAL_URL}"
echo "  KnowledgeHub Admin:   http://localhost:8001"
echo ""
if [ "$PROXY_ONLY" = false ]; then
    echo "  Pipeline Mode: ENABLED"
    echo "  Configure Valves at: Admin Panel → Settings → Pipelines"
else
    echo "  Proxy Mode: ENABLED (no pipeline)"
fi
echo ""
echo "═══════════════════════════════════════════════════════════════"
